[build]
  command = "npm install"
  publish = "."

[functions]
  external_node_modules = ["express", "@whiskeysockets/baileys", "maher-zubair-baileys", "qrcode", "awesome-phonenumber", "pino", "phone", "body-parser", "pastebin-js", "path"]

[[functions]]
  name = "server"
  path = "/.netlify/functions/server"
  handler = "netlify/functions/mbuvi.handler"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200