[build]
  command = "npm install"
  publish = "."

[[functions]]
  function = "server"
  handler = "mbuvi.handler"
  external_node_modules = ["express", "@whiskeysockets/baileys", "maher-zubair-baileys", "qrcode", "awesome-phonenumber", "pino", "phone", "body-parser", "pastebin-js", "path"]